update
upgrade
tap caskroom/cask
tap caskroom/fonts
tap caskroom/versions
tap homebrew/core
tap homebrew/dupes
tap josegonzalez/php
install ack
install autoconf
install bash
install boost
install c-ares
install cmake
install coreutils
install curl
install findutils
install fontconfig
install freetype
install gd
install gdbm
install gettext
install git
install gnu-tar
install graphviz
install grc
install grep
install httpie
install hub
install hugo
install jansson
install jemalloc
install jpeg
install jq
install libev
install libevent
install libidn
install libpng
install libtiff
install libtool
install libxml2
install libyaml
install maven
install mongodb
install mysql
install nghttp2
install node
install oniguruma
install openssl
install pcre
install perl
install pkg-config
install python
install python3
install rbenv
install readline
install reattach-to-user-namespace
install redis
install rename
install ruby
install ruby-build
install spark
install spdylay
install sqlite
install the_silver_searcher
install tmux
install tree
install varnish
install vim
install watch
install webp
install wget
install xz
install yarn
install z
install zsh
cask install alfred
cask install bittorrent-sync (!)
cask install charles
cask install divvy
cask install font-sauce-code-powerline (!)
cask install font-source-code-pro
cask install google-chrome
cask install imageoptim
cask install iterm2-nightly
cask install java
cask install licecap
cask install slack
cask install sonos
cask install spotify
cask install sublime-text-dev
cask install virtualbox
cask install vlc
cleanup
