# Install global deps
npm install -g jshint
npm install -g eslint
npm install -g eslint_d
npm install -g typescript
npm install -g babel-cli
npm install -g babel-eslint
npm install -g bower
npm install -g rollup
npm install -g vtop
